site_name: Visual Studio Code Tips
theme:
  name: material
  logo: images/vscode-icon.svg
  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy   
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: cyan
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: cyan

nav:
    - 'index.md'
    - 'ediljohn - page2.md'
    - 'collin - page3.md'
    - 'collin - page4.md'
    - 'glossary.md'
    - 'troubleshooting.md'

copyright: |
  &copy; Collin and Ediljohn
